---
title: "Clustering demographic data"
author: "Brian"
date: "2/27/2022"
output: html_document
---

# loading the libraries
```{r}
library(tidyverse)
library(cluster)
library(viridis)
library(leaflet)
library(mapview)
library(tmap)
library(sf)
library(purrr)
library(arsenal)
```

# loading the data
```{r}
demographics <- read_rds("demographics.rds")
demographics %>% head()
```

# settting the distance matrix
```{r}
set.seed(23994)
vars <- demographics %>% select(-GEOID, -county, -state, -geometry) %>% colnames()
distance_matrix <- cluster::daisy(demographics[,vars])
res.pam <- cluster::pam(x=distance_matrix, k = 5, cluster.only = F)
demographics$cluster <- as.double(res.pam$clustering) 
                              
```

```{r}
demographics %>% filter(county == "King County" & state == "Washington") %>% select(cluster)
demographics_match <- demographics %>% filter(cluster == 4)
demographics_match %>% select(vars) %>% summary()
```

# making a table
```{r}
data <- demographics %>% select(vars) 
sum_stats <- data %>%                            
  split(.$cluster) %>%
  map(summary)
sum_stats
#table(demographics$cluster, exclude = 'nothing')
```
Method 2
```{r}
table_one <- tableby(cluster ~ ., data = data)
summary(table_one, title = "Summary Statistics")
```
Method 3
```{r}
sum_stats <- data %>% group_by(cluster) %>% summarise(avg_income = mean(medinc),
sd = sd(medinc))
```

# quick plot
```{r}
demographics %>% mutate(cluster = as.factor(cluster)) %>%
  ggplot(aes(cluster, medinc))+
  geom_boxplot()
```



# quick map
```{r}
demographics %>% filter(cluster == 4) %>% st_sf() %>% mapview(zcol = "cluster")
```

```{r}
demographics_sample <- demographics_match %>%
  slice_sample(n = 40)
demographics_sample %>% select(county, state)
```

